export enum StatusEnum {
    confirmed,
    deaths,
    recovered
}

export enum CountryEnum {
    
    Afghanistan = "afghanistan",
    Albania = "albania",
    Algeria = "algeria",
    Andorra = "andorra",
    Angola = "angola",
    Antigua_and_Barbuda = "antigua-and-barbuda",
    Argentina = "argentina",
    Armenia = "armenia",
    Aruba = "aruba",
    Australia
    ="australia",
    Austria
    ="austria",
    Azerbaijan
    ="azerbaijan",
    Bahamas_The
    ="bahamas-the",
    Bahrain
    ="bahrain",
    Bangladesh
    ="bangladesh",
    Barbados
    ="barbados",
    Belarus
    ="belarus",
    Belgium
    ="belgium",
    Benin
    ="benin",
    Bhutan
    ="bhutan",
    Bolivia
    ="bolivia",
    Bosnia_and_Herzegovina
    ="bosnia-and-herzegovina",
    Brazil
    ="brazil",
    Brunei
    ="brunei",
    Bulgaria
    ="bulgaria",
    Burkina_Faso
    ="burkina-faso",
    Cabo_Verde
    ="cabo-verde",
    Cambodia
    ="cambodia",
    Cameroon
    ="cameroon",
    Canada
    ="canada",
    Central_African_Republic
    ="central-african-republic",
    Chad
    ="chad",
    Chile
    ="chile",
    China
    ="china",
    Colombia
    ="colombia",
    Congo_Brazzaville
    ="congo-(brazzaville)",
    Congo_Kinshasa
    ="congo-(kinshasa)",
    Costa_Rica
    ="costa-rica",
    Cote_dIvoire
    ="cote-divoire",
    Croatia
    ="croatia",
    Cruise_Ship
    ="cruise-ship",
    Cuba
    ="cuba",
    Cyprus
    ="cyprus",
    Czechia
    ="czechia",
    Denmark
    ="denmark",
    Djibouti
    ="djibouti",
    Dominican_Republic
    ="dominican-republic",
    Ecuador
    ="ecuador",
    Egypt
    ="egypt",
    El_Salvador
    ="el-salvador",
    Equatorial_Guinea
    ="equatorial-guinea",
    Estonia
    ="estonia",
    Eswatini
    ="eswatini",
    Ethiopia
    ="ethiopia",
    Fiji
    ="fiji",
    Finland
    ="finland",
    France
    ="france",
    French_Guiana
    ="french-guiana",
    Gabon
    ="gabon",
    Gambia_The
    ="gambia-the",
    Georgia
    ="georgia",
    Germany
    ="germany",
    Ghana
    ="ghana",
    Greece
    ="greece",
    Greenland
    ="greenland",
    Guadeloupe
    ="guadeloupe",
    Guam
    ="guam",
    Guatemala
    ="guatemala",
    Guernsey
    ="guernsey",
    Guinea
    ="guinea",
    Guyana
    ="guyana",
    Haiti
    ="haiti",
    Holy_See
    ="holy-see",
    Honduras
    ="honduras",
    Hungary
    ="hungary",
    Iceland
    ="iceland",
    India
    ="india",
    Indonesia
    ="indonesia",
    Iran
    ="iran",
    Iraq
    ="iraq",
    Ireland
    ="ireland",
    Israel
    ="israel",
    Italy
    ="italy",
    Jamaica
    ="jamaica",
    Japan
    ="japan",
    Jersey
    ="jersey",
    Jordan
    ="jordan",
    Kazakhstan
    ="kazakhstan",
    Kenya
    ="kenya",
    Korea_South
    ="korea-south",
    Kosovo
    ="kosovo",
    Kuwait
    ="kuwait",
    Kyrgyzstan
    ="kyrgyzstan",
    Latvia
    ="latvia",
    Lebanon
    ="lebanon",
    Liberia
    ="liberia",
    Liechtenstein
    ="liechtenstein",
    Lithuania
    ="lithuania",
    Luxembourg
    ="luxembourg",
    Madagascar
    ="madagascar",
    Malaysia
    ="malaysia",
    Maldives
    ="maldives",
    Malta
    ="malta",
    Martinique
    ="martinique",
    Mauritania
    ="mauritania",
    Mauritius
    ="mauritius",
    Mayotte
    ="mayotte",
    Mexico
    ="mexico",
    Moldova
    ="moldova",
    Monaco
    ="monaco",
    Mongolia
    ="mongolia",
    Montenegro
    ="montenegro",
    Morocco
    ="morocco",
    Namibia
    ="namibia",
    Nepal
    ="nepal",
    Netherlands
    ="netherlands",
    New_Zealand
    ="new-zealand",
    Nicaragua
    ="nicaragua",
    Niger
    ="niger",
    Nigeria
    ="nigeria",
    North_Macedonia
    ="north-macedonia",
    Norway
    ="norway",
    occupied_Palestinian_territory
    ="occupied-palestinian-territory",
    Oman
    ="oman",
    Pakistan
    ="pakistan",
    Panama
    ="panama",
    Papua_New_Guinea
    ="papua-new-guinea",
    Paraguay
    ="paraguay",
    Peru
    ="peru",
    Philippines
    ="philippines",
    Poland
    ="poland",
    Portugal
    ="portugal",
    Puerto_Rico
    ="puerto-rico",
    Qatar
    ="qatar",
    Republic_of_the_Congo
    ="republic-of-the-congo",
    Reunion
    ="reunion",
    Romania
    ="romania",
    Russia
    ="russia",
    Rwanda
    ="rwanda",
    Saint_Lucia
    ="saint-lucia",
    Saint_Vincent_and_the_Grenadines
    ="saint-vincent-and-the-grenadines",
    San_Marino
    ="san-marino",
    Saudi_Arabia
    ="saudi-arabia",
    Senegal
    ="senegal",
    Serbia
    ="serbia",
    Seychelles
    ="seychelles",
    Singapore
    ="singapore",
    Slovakia
    ="slovakia",
    Slovenia
    ="slovenia",
    Somalia
    ="somalia",
    South_Africa
    ="south-africa",
    Spain
    ="spain",
    Sri_Lanka
    ="sri-lanka",
    Sudan
    ="sudan",
    Suriname
    ="suriname",
    Sweden
    ="sweden",
    Switzerland
    ="switzerland",
    Taiwan
    ="taiwan",
    Tanzania
    ="tanzania",
    Thailand
    ="thailand",
    The_Bahamas
    ="the-bahamas",
    The_Gambia
    ="the-gambia",
    Togo
    ="togo",
    Trinidad_and_Tobago
    ="trinidad-and-tobago",
    Tunisia
    ="tunisia",
    Turkey
    ="turkey",
    Ukraine
    ="ukraine",
    United_Arab_Emirates
    ="united-arab-emirates",
    United_Kingdom
    ="united-kingdom",
    Uruguay = "uruguay",
    US = "us",
    Uzbekistan = "uzbekistan",
    Venezuela = "venezuela",
    Vietnam = "vietnam",
    Zambia = "zambia",
    Zimbabwe = "zimbabwe"
}